version: "3"
services:
  express-server:
    build: .
    image: ${DOCKERHUB_NAME}/${IMAGE_NAME}:${IMAGE_VERSION}
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    expose:
      - 3000